wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1672929468.183272
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.9.7
      5: 0.13.7
      8:
      - 5
epochs:
  desc: null
  value: 15
lr:
  desc: null
  value: 0.046148410367374305
